### ISSUE TITLE
What is expected with "cleaning"?

### ISSUE THREAD

**Issue by TimmermanIDS** [RUG-IDS/Course-2017#10]
The exercise asks that we clean the data in the movievalue.csv file. We're not entirely sure what is meant by this though. Does this mean for instance that movies with unreadable titles should be removed, and that unknown data should be properly marked as unknown?

**Comment by rm-bwana** [comment]
Cleaning can take several forms:

1. The simplest one is just to get rid of any information that is unreadable or unusable. 

2. Another more complex approach is to try and see if the 'unreadability' of the title can be predicted or fixed in any way so that you do not have to get rid of it. (e.g. think of encoding errors here)

3. Perhaps the most complex form is to try and fix it based on any other information that is linked to it. (e.g. Trying to predict title by other key attributes)

We leave it up to you as to how much of the challenge you wish to take up. Just ensure that you explain how you handled it and why you chose to do what you chose to do. Also important to ensure is that whatever you choose to do does not lead to incorrect analysis further on.

**Comment by Daemonstool** [comment]
I assume that getting rid of any information boils down to removing an entire entry of the CSV file? Isn't that a bad idea since other feature information might still be useful for other questions?

**Comment by rm-bwana** [comment]
That is indeed the disadvantage of the simplest option. If you remove data you may always lose some accuracy in any analysis you perform afterwards. In some cases the accuracy lost is mostly trivial. Other times it could be vital. It is up to you to determine how best to deal with it.
