### ISSUE TITLE
Bagging and boosting

### ISSUE THREAD

**Issue by wouterMostard** [RUG-IDS/Course-2017#13]
Hi all,

I am reading up on bagging and boosting on the presentation assignment next week. We are presenting about sampling and one thing isn't really clear.

In the lecture it is shown that bagging and boosting are types of ensemble methods, thus methods for improving the model by using various models or types. How can I relate this to the sampling problem? Is it such that sampling is a model as such and for example boosting can help pick better attributes for sampling? 

Thank you in advance.

Wouter

**Comment by rm-bwana** [comment]
A sample may be argued to be considered a model in its simplest sense, but I would also consider the following: 

Bagging and boosting, as you correctly stated, are ensemble methods (and you may wish to explain what ensemble methods mean in your presentation for those not familiar with it as it helps with the understanding of the two methods), however their final output is not a better sample but rather they use forms of sampling in their process.

If you are presenting on sampling what could be of interest for your presentation is the differing ways of sampling they employ to come to their output.

Perhaps we should keep this issue open so that the 4 other groups presenting on this topic can also contribute to the discussion.

**Comment by rm-bwana** [comment]
The topic is also discussed in the book recommended to you so with some research and reading (a big part of the next 2 assignments) you may find a more detailed answer than the one I just gave. 

Of course if there is anything you do not understand let us know.

**Comment by jasperdev** [comment]
I guess the bootstrapping part of bagging is highly relevant when your topic is sampling:
https://en.wikipedia.org/wiki/Bootstrapping_%28statistics%29

**Comment by wouterMostard** [comment]
Thank for the responses, it is a lot clearer how. One thing I still don't really get though. What is the relationship between sampling and for example boosting? The only thing that boosting does is picking the data objects that are hard to classify and giving more weights to them such that the model improves right?

**Comment by rm-bwana** [comment]
Could you not argue that **picking the data object that are hard to classify** is a form of sampling? Like mentioned sampling is just a step of the boosting procedure.
