### ISSUE TITLE
Data in notebooks 

### ISSUE THREAD

**Issue by wouterMostard** [RUG-IDS/Course-2017#17]
Hi all,

Will the notebooks be run after submission? I ran the notebook and uploaded the jupyter notebook including the results but excluding the data.

The data has been excluded by design since it takes up a lot of space and in my opinion it defeats the purpose of a notebook presentation.

**Comment by rm-bwana** [comment]
Hello Wouter,

For this assignment we won't be fully testing code uploaded as per the previous assignment. Any code submitted will be considered as supporting material for the presentations and subsequent reports rather than a separate item to be graded. 

While we hope that the code submitted was relevant and correct and may choose to test it, should we need the data we will ask you to provide it.
