### ISSUE TITLE
Bonus assignment excluded from the total word count?

### ISSUE THREAD

**Issue by KlaasYK** [RUG-IDS/Course-2017#18]
The third assignment poses a limit of ~1800 words, I suppose the bonus assignment is excluded from this word count and the total number of words can be a bit higher?

**Comment by rm-bwana** [comment]
1800 words are more a target to aim for rather than a fixed rule. What is most important is that the relevant information is included in the report as clearly and concisely as possible. 

The bonus assignment is considered separately from that word count as otherwise those not doing the bonus would have more to write in their main report.
