### ISSUE TITLE
Eigen value decomposition of features

### ISSUE THREAD

**Issue by wouterMostard** [RUG-IDS/Course-2017#23]
Hi all, 

The first assignment asks us to decompose the features array into eigen values and perform ANOVA. 

The problem with eigen values is that the features matrix isn't square (359,186) and thus calculating the eigen values is not possible. A possible solution would be to square the matrix by using only half the rows; but I can imagine this is something you absolutely don't want to do. There isn't a way to calculate the eigen values from a non square matrix right?

**Comment by kbunte** [comment]
You might want to check if the implementation you are using is requiring a covariance matrix as input. 
In that case you need to build that first.

**Comment by sreejita-rug** [comment]
1) **problem with eigen values is that the features matrix isn't square (359,186) and thus calculating the eigen values is not possible**- Yes, ofcourse not. But in order to get the principal components via eigen value decomposition you have to do eigen value decomposition on the covariance matrix of the data (and the covariance matrix is a square matrix). Else use pca function
2) And perform a) ANOVA and b) Eigen value decomposition or PCA, separately, and **not** one after the other
.
