### ISSUE TITLE
Assignment 6 not available yet

### ISSUE THREAD

**Issue by Daemonstool** [RUG-IDS/Course-2017#27]
Dear TAs and lecturers,

We would appreciate it if the next assignment is made available. I think it is a bit unreasonable to publish the assignment that late and still expect us to hand in the assignment on Sunday. The assignments should be made available as soon as possible after the lecture. Now we only have a couple of working days to work on the assignment and we also have to balance our workload over different courses and other obligations. 

Best, 
Henry on behalf of team-9

**Comment by sreejita-rug** [comment]
1) **Why assignment 6 not uploaded after class hours**: Since the deadline of the classification assignment was extended till tonight due to a number of your fellow teams who were struggling to keep up with the original deadline, we hadn't uploaded the assignment for this week yet. You aren't the only ones with workload, but unlike you guys there are some not-so-capable teams, and we wanted to cut them some slack despite our own workload. Uploading new assignment when they are yet to submit the previous one  would have stressed these teams out even more. But you are right, always, and we are wrong.
2) **Workload**: The courses of other TAs, and my own research work, going through the submitted assignments of all the teams, grading and giving our feedback, designing the next assignment for you guys by trying out different problems and filtering out only the ones which the majority of you will be able to submit within the deadline,  plus tending to our other obligations- but sure, we the people on the other side of the table don't have any workload. Right!

Also thank you for keeping up your good job of always pointing out our faults. From the next time we will try to keep in mind the extreme hassles which our considerations towards the struggling teams,  put you guys through. I mean sure, let the struggling teams suffer, right? And ofcourse the other teams for whom we extended the deadline, probably do not have half as much workload as you guys, right? So ofcourse we made a mistake by trying to give a chance to other teams.
Also I am sorry on behalf of the TAs that we haven't yet responded to any of your thoughtful feedback about us. This time onwards you'll get the answers from us for your allegations against us, answers which you rightfully deserve :) 
Best regards,
Sreejita

**Comment by GreenpantsDeveloper** [comment]
Huh?

I'm in a so-called _"not-so-capable"_ team.
How exactly would it be bad for me, if the next assignment would be uploaded in time so that the early groups can at least plan ahead?

**Comment by sreejita-rug** [comment]
We will not in be unfair wrt time allotted to you to complete your assignments. When you receive the assignment late from us because of extended deadline of previous assignment, the deadline for the next assignment has also been adjusted accordingly. But thanks for letting us know that it is actually easier for everyone to work on and plan on assignments from two different topics simultaneously.
