### ISSUE TITLE
Assignment 7 exercise 3.1 ambiguity

### ISSUE THREAD

**Issue by sietzehouwink** [RUG-IDS/Course-2017#34]
Dear reader,

In what direction do you expect an answer to exercise 3.1; 'What differences are there between the 3d and 6d data?', as this question is also asked in exercise 2.2 and is quite general? Thank you in advance.

Yours sincerely,
Patrick Vogel & Sietze Houwink

**Comment by joelgrondman** [comment]
Hi Sietze,

The questions should be answered by using dendograms or K-means in some way, e.g. for 2.2 you can create a dendogram and say something about how the stars are clustered together using agglomerative clustering . Agglomerative clustering and K-means are completely different techniques for finding clusters. That's why we asked this question twice.
